AWSTemplateFormatVersion: '2010-09-09'
Description: Provision an EC2 instance with NGINX in a public subnet using CloudFormation

Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  KeyPairName:
    Description: Key Pair for EC2
    Type: 'AWS::EC2::KeyPair::KeyName'


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: t2.micro
      ImageId: ami-04e35eeae7a7c5883  # Replace with the Linux 2023 AMI ID
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello CloudFormation from $(hostname -f)</h1>" > /var/www/html/index.html
      

  WebAppSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: 'Allow HTTP/HTTPS and SSH inbound and outbound traffic'
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0

  WebAppEIP: #elastic IP so we have just one IP!
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc
        InstanceId: !Ref EC2Instance
        Tags:
          - Key: Name
            Value: !Join [ '-', [ webapp-eip, webapp-eip  ] ]
        
 
Outputs:
  WebsiteURL:
    Value: !Sub http://${WebAppEIP}
    Description: WebApp URL


